### ISSUE TITLE
Controlling for months spent learning to code, how is attending in-person coding events correlated with getting a job?

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/2016-new-coder-survey#23]

**Comment by SamAI-Software** [comment]
Connected:

MonthsProgramming+JobPref

> Would you prefer to work for a startup, start your own business, work for a multinational corporation, work for a medium-sized company or freelance?

- Almost **90%** of respondents who code for **less than 1 year** have preferences about their job, while **most of coders** (**76%**) with **5+ years** of programming experience are ready to work in a company of any size and even freelance or start their own business.

![monthsprogramming jobpref 720](https://cloud.githubusercontent.com/assets/16253583/15273548/570acd84-1ac7-11e6-838a-819e1d40bcb4.jpeg)

**Comment by chessybo** [comment]
of those that got a job, we only have an answers for people that attended a coding bootcamp. its not possible to answer this.

**Comment by QuincyLarson** [comment]
@chessybo OK - thanks for looking into this! I'll try to restructure next year's survey to make this data available.
