### ISSUE TITLE
Check map data

### ISSUE THREAD

**Issue by SamAI-Software** [FreeCodeCamp/2016-new-coder-survey#73]
@krisgesling @sunydyz

**Comment by ghost** [comment]
Hello. Upon further research, this may be more of a question than an issue. I was comparing the total field in maps-data.json with https://github.com/FreeCodeCamp/2016-new-coder-survey/tree/master/clean-data.  For the United States (for instance), in maps-data.json I see 6,265.  In https://github.com/FreeCodeCamp/2016-new-coder-survey/tree/master/clean-data there appear to be 5,976 total respondents for the United States.  I think the difference is between the CountryCitizen and CountryLive fields.  So my question is: should the total in this instance be 5976 for the United States or 6,265? Thanks.

**Comment by krisgesling** [comment]
Hi Sunydyz, you are right, the difference is whether you want to look at where people are citizens vs where they are living. 

I started off looking at citizens but changed it to where people are living and therefore where the coding is actually happening, as I thought this made more sense for the purpose of this survey. I then added the hover over graph to show what proportion of people were citizens of where they were living.

@SamAI-Software is that the only data that needs checking?

**Comment by SamAI-Software** [comment]
@krisgesling that's all for now, but also @sunydyz is working on making a map with more data, so you can probably help him out if he have questions.
Feel free to use gitter or this issue, so I can also follow the conversation.

**Comment by krisgesling** [comment]
Yeah no worries, we've been messaging in Gitter already. Is there anything else you need help with to get the page finalised?
You've done a mammoth job on it all!

**Comment by SamAI-Software** [comment]
It's an on-going process, we will keep adding visualizations as new contributors will come :)
